# Generated by Django 3.0.4 on 2020-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
